### ISSUE TITLE
关于核心函数入口的保护 来自issues#12的疑问

### ISSUE THREAD

**Issue by hong4k** [sablejs/sablejs#15]
https://github.com/sablejs/sablejs/issues/12

在issues#12展示了，如何在外部调用使用sablejs保护的函数。但是存在的问题是，这个函数的入口和出口在前端是可以调试出来的，只是函数内部的逻辑不可见。也就是前端可以解耦出关键函数来，不需要知道内部具体逻辑，方便爬虫或者攻击。

由于sablejs的vm里不支持location对象，所以通过限制域名在当前域名下使用也行不通。
那么sablejs如何才能有效避免函数劫持呢？今后有这方便计划么？

**Comment by ErosZy** [comment]
@hong4k i can give you two keypoints:

1. Your code should be as strongly coupled to the browser environment as possible. In YoTest, we traverse basically all the DOMs and BOMs and then bind them to the VM for use, YoTest contains a lot of DOM/BOM operations inside, if you just use Nodejs/Python... to run it directly, it will run with errors due to the lack of DOM/BOM APIs.

2. You can't just rely on the DOM/BOM to do your defense, you need to rely on your other business processes as well.

Based on these two points, it is very difficult to rely on DOM/BOM simulation and tampering to make calls in YoTest.

**Comment by hong4k** [comment]
Got it
Thx 4 reply
